pub(crate) const DEFAULT_FLIES_OVER_TTL_SECONDS: i64 = 180;
pub(crate) const DEFAULT_RELATION_SWEEP_INTERVAL_SECONDS: u64 = 30;
pub(crate) const DEFAULT_NEAREST_ZONE_MAX_DISTANCE_KM: f64 = 100.0;
pub(crate) const DEFAULT_TABLE_CACHE_TTL_MS: u64 = 2_000;
pub(crate) const MONITORED_BY_MAX_DISTANCE_KM: f64 = 2.0;
pub(crate) const LOW_VISIBILITY_THRESHOLD_M: f64 = 1000.0;
