use crate::GraphClient;

const ENTITY_TABLES: &[&str] = &[
    "zone",
    "aircraft",
    "camera",
    "weather",
    "traffic_segment",
    "satellite",
    "event",
    "alert",
    "cable",
    "landing_point",
    "seismic_event",
    "fire_hotspot",
    "gdelt_event",
    "vessel",
    "cyber_threat",
    "space_weather_event",
    "aurora_point",
    "space_weather_alert",
    "military_base",
    "nuclear_site",
];

const RELATION_TABLES: &[&str] = &[
    "located_in",
    "flies_over",
    "monitored_by",
    "affected_by",
    "triggered",
    "observes",
    "covers",
    "passes_over",
    "involves",
    "connects_to",
    "reports",
    "near",
    "targets",
    "derived_from",
];

const FIELD_DEFINITIONS: &[&str] = &[
    "DEFINE FIELD id ON TABLE zone TYPE string;",
    "DEFINE FIELD name ON TABLE zone TYPE string;",
    "DEFINE FIELD type ON TABLE zone TYPE string;",
    "DEFINE FIELD country ON TABLE zone TYPE string;",
    "DEFINE FIELD geometry ON TABLE zone TYPE object;",
    "DEFINE FIELD centroid ON TABLE zone TYPE array;",
    "DEFINE FIELD bbox ON TABLE zone TYPE array;",
    "DEFINE FIELD icao ON TABLE aircraft TYPE string;",
    "DEFINE FIELD callsign ON TABLE aircraft TYPE string;",
    "DEFINE FIELD lat ON TABLE aircraft TYPE number;",
    "DEFINE FIELD lon ON TABLE aircraft TYPE number;",
    "DEFINE FIELD altitude ON TABLE aircraft TYPE number;",
    "DEFINE FIELD speed ON TABLE aircraft TYPE number;",
    "DEFINE FIELD heading ON TABLE aircraft TYPE number;",
    "DEFINE FIELD timestamp ON TABLE aircraft TYPE datetime;",
    "DEFINE FIELD id ON TABLE camera TYPE string;",
    "DEFINE FIELD name ON TABLE camera TYPE string;",
    "DEFINE FIELD stream_type ON TABLE camera TYPE string;",
    "DEFINE FIELD source ON TABLE camera TYPE string;",
    "DEFINE FIELD is_online ON TABLE camera TYPE bool;",
    "DEFINE FIELD lat ON TABLE camera TYPE number;",
    "DEFINE FIELD lon ON TABLE camera TYPE number;",
    "DEFINE FIELD last_seen ON TABLE camera TYPE datetime;",
    "DEFINE FIELD station_id ON TABLE weather TYPE string;",
    "DEFINE FIELD city ON TABLE weather TYPE string;",
    "DEFINE FIELD lat ON TABLE weather TYPE number;",
    "DEFINE FIELD lon ON TABLE weather TYPE number;",
    "DEFINE FIELD temp ON TABLE weather TYPE number;",
    "DEFINE FIELD wind ON TABLE weather TYPE number;",
    "DEFINE FIELD visibility ON TABLE weather TYPE number;",
    "DEFINE FIELD conditions ON TABLE weather TYPE string;",
    "DEFINE FIELD timestamp ON TABLE weather TYPE datetime;",
    "DEFINE FIELD segment_id ON TABLE traffic_segment TYPE string;",
    "DEFINE FIELD road_name ON TABLE traffic_segment TYPE string;",
    "DEFINE FIELD lat ON TABLE traffic_segment TYPE number;",
    "DEFINE FIELD lon ON TABLE traffic_segment TYPE number;",
    "DEFINE FIELD speed_ratio ON TABLE traffic_segment TYPE number;",
    "DEFINE FIELD delay_min ON TABLE traffic_segment TYPE number;",
    "DEFINE FIELD severity ON TABLE traffic_segment TYPE string;",
    "DEFINE FIELD timestamp ON TABLE traffic_segment TYPE datetime;",
    "DEFINE FIELD norad_id ON TABLE satellite TYPE number;",
    "DEFINE FIELD name ON TABLE satellite TYPE string;",
    "DEFINE FIELD category ON TABLE satellite TYPE string;",
    "DEFINE FIELD lat ON TABLE satellite TYPE number;",
    "DEFINE FIELD lon ON TABLE satellite TYPE number;",
    "DEFINE FIELD altitude_km ON TABLE satellite TYPE number;",
    "DEFINE FIELD velocity_kmh ON TABLE satellite TYPE number;",
    "DEFINE FIELD timestamp ON TABLE satellite TYPE datetime;",
    "DEFINE FIELD id ON TABLE event TYPE string;",
    "DEFINE FIELD type ON TABLE event TYPE string;",
    "DEFINE FIELD severity ON TABLE event TYPE string;",
    "DEFINE FIELD description ON TABLE event TYPE string;",
    "DEFINE FIELD lat ON TABLE event TYPE number;",
    "DEFINE FIELD lon ON TABLE event TYPE number;",
    "DEFINE FIELD timestamp ON TABLE event TYPE datetime;",
    "DEFINE FIELD id ON TABLE alert TYPE string;",
    "DEFINE FIELD type ON TABLE alert TYPE string;",
    "DEFINE FIELD severity ON TABLE alert TYPE string;",
    "DEFINE FIELD message ON TABLE alert TYPE string;",
    "DEFINE FIELD entities ON TABLE alert TYPE array;",
    "DEFINE FIELD timestamp ON TABLE alert TYPE datetime;",
    "DEFINE FIELD id ON TABLE cable TYPE string;",
    "DEFINE FIELD name ON TABLE cable TYPE string;",
    "DEFINE FIELD status ON TABLE cable TYPE string;",
    "DEFINE FIELD owners ON TABLE cable TYPE array;",
    "DEFINE FIELD length_km ON TABLE cable TYPE number;",
    "DEFINE FIELD geometry ON TABLE cable TYPE object;",
    "DEFINE FIELD id ON TABLE landing_point TYPE string;",
    "DEFINE FIELD name ON TABLE landing_point TYPE string;",
    "DEFINE FIELD country ON TABLE landing_point TYPE string;",
    "DEFINE FIELD lat ON TABLE landing_point TYPE number;",
    "DEFINE FIELD lon ON TABLE landing_point TYPE number;",
    "DEFINE FIELD cable_ids ON TABLE landing_point TYPE array;",
    "DEFINE FIELD id ON TABLE seismic_event TYPE string;",
    "DEFINE FIELD magnitude ON TABLE seismic_event TYPE number;",
    "DEFINE FIELD depth_km ON TABLE seismic_event TYPE number;",
    "DEFINE FIELD lat ON TABLE seismic_event TYPE number;",
    "DEFINE FIELD lon ON TABLE seismic_event TYPE number;",
    "DEFINE FIELD region ON TABLE seismic_event TYPE string;",
    "DEFINE FIELD timestamp ON TABLE seismic_event TYPE datetime;",
    "DEFINE FIELD id ON TABLE fire_hotspot TYPE string;",
    "DEFINE FIELD lat ON TABLE fire_hotspot TYPE number;",
    "DEFINE FIELD lon ON TABLE fire_hotspot TYPE number;",
    "DEFINE FIELD brightness ON TABLE fire_hotspot TYPE number;",
    "DEFINE FIELD confidence ON TABLE fire_hotspot TYPE number;",
    "DEFINE FIELD satellite ON TABLE fire_hotspot TYPE string;",
    "DEFINE FIELD timestamp ON TABLE fire_hotspot TYPE datetime;",
    "DEFINE FIELD id ON TABLE gdelt_event TYPE string;",
    "DEFINE FIELD source ON TABLE gdelt_event TYPE string;",
    "DEFINE FIELD url ON TABLE gdelt_event TYPE string;",
    "DEFINE FIELD tone ON TABLE gdelt_event TYPE number;",
    "DEFINE FIELD summary ON TABLE gdelt_event TYPE string;",
    "DEFINE FIELD lat ON TABLE gdelt_event TYPE number;",
    "DEFINE FIELD lon ON TABLE gdelt_event TYPE number;",
    "DEFINE FIELD timestamp ON TABLE gdelt_event TYPE datetime;",
    "DEFINE FIELD mmsi ON TABLE vessel TYPE string;",
    "DEFINE FIELD name ON TABLE vessel TYPE string;",
    "DEFINE FIELD lat ON TABLE vessel TYPE number;",
    "DEFINE FIELD lon ON TABLE vessel TYPE number;",
    "DEFINE FIELD sog_knots ON TABLE vessel TYPE number;",
    "DEFINE FIELD cog ON TABLE vessel TYPE number;",
    "DEFINE FIELD heading ON TABLE vessel TYPE number;",
    "DEFINE FIELD timestamp ON TABLE vessel TYPE datetime;",
    "DEFINE FIELD id ON TABLE cyber_threat TYPE string;",
    "DEFINE FIELD ioc ON TABLE cyber_threat TYPE string;",
    "DEFINE FIELD ioc_type ON TABLE cyber_threat TYPE string;",
    "DEFINE FIELD severity ON TABLE cyber_threat TYPE string;",
    "DEFINE FIELD source ON TABLE cyber_threat TYPE string;",
    "DEFINE FIELD target ON TABLE cyber_threat TYPE string;",
    "DEFINE FIELD timestamp ON TABLE cyber_threat TYPE datetime;",
    "DEFINE FIELD id ON TABLE space_weather_event TYPE string;",
    "DEFINE FIELD event_type ON TABLE space_weather_event TYPE string;",
    "DEFINE FIELD severity ON TABLE space_weather_event TYPE string;",
    "DEFINE FIELD summary ON TABLE space_weather_event TYPE string;",
    "DEFINE FIELD kp_index ON TABLE space_weather_event TYPE number;",
    "DEFINE FIELD start_time ON TABLE space_weather_event TYPE datetime;",
    "DEFINE FIELD end_time ON TABLE space_weather_event TYPE datetime;",
    "DEFINE FIELD id ON TABLE aurora_point TYPE string;",
    "DEFINE FIELD lat ON TABLE aurora_point TYPE number;",
    "DEFINE FIELD lon ON TABLE aurora_point TYPE number;",
    "DEFINE FIELD intensity ON TABLE aurora_point TYPE number;",
    "DEFINE FIELD timestamp ON TABLE aurora_point TYPE datetime;",
    "DEFINE FIELD id ON TABLE space_weather_alert TYPE string;",
    "DEFINE FIELD alert_type ON TABLE space_weather_alert TYPE string;",
    "DEFINE FIELD severity ON TABLE space_weather_alert TYPE string;",
    "DEFINE FIELD message ON TABLE space_weather_alert TYPE string;",
    "DEFINE FIELD timestamp ON TABLE space_weather_alert TYPE datetime;",
    "DEFINE FIELD id ON TABLE military_base TYPE string;",
    "DEFINE FIELD name ON TABLE military_base TYPE string;",
    "DEFINE FIELD country ON TABLE military_base TYPE string;",
    "DEFINE FIELD category ON TABLE military_base TYPE string;",
    "DEFINE FIELD lat ON TABLE military_base TYPE number;",
    "DEFINE FIELD lon ON TABLE military_base TYPE number;",
    "DEFINE FIELD id ON TABLE nuclear_site TYPE string;",
    "DEFINE FIELD name ON TABLE nuclear_site TYPE string;",
    "DEFINE FIELD country ON TABLE nuclear_site TYPE string;",
    "DEFINE FIELD site_type ON TABLE nuclear_site TYPE string;",
    "DEFINE FIELD status ON TABLE nuclear_site TYPE string;",
    "DEFINE FIELD lat ON TABLE nuclear_site TYPE number;",
    "DEFINE FIELD lon ON TABLE nuclear_site TYPE number;",
    "DEFINE FIELD source ON TABLE located_in TYPE string;",
    "DEFINE FIELD score ON TABLE located_in TYPE number;",
    "DEFINE FIELD timestamp ON TABLE located_in TYPE datetime;",
    "DEFINE FIELD source ON TABLE flies_over TYPE string;",
    "DEFINE FIELD score ON TABLE flies_over TYPE number;",
    "DEFINE FIELD timestamp ON TABLE flies_over TYPE datetime;",
    "DEFINE FIELD source ON TABLE monitored_by TYPE string;",
    "DEFINE FIELD score ON TABLE monitored_by TYPE number;",
    "DEFINE FIELD timestamp ON TABLE monitored_by TYPE datetime;",
    "DEFINE FIELD source ON TABLE affected_by TYPE string;",
    "DEFINE FIELD score ON TABLE affected_by TYPE number;",
    "DEFINE FIELD timestamp ON TABLE affected_by TYPE datetime;",
    "DEFINE FIELD source ON TABLE triggered TYPE string;",
    "DEFINE FIELD score ON TABLE triggered TYPE number;",
    "DEFINE FIELD timestamp ON TABLE triggered TYPE datetime;",
    "DEFINE FIELD source ON TABLE observes TYPE string;",
    "DEFINE FIELD score ON TABLE observes TYPE number;",
    "DEFINE FIELD timestamp ON TABLE observes TYPE datetime;",
    "DEFINE FIELD source ON TABLE covers TYPE string;",
    "DEFINE FIELD score ON TABLE covers TYPE number;",
    "DEFINE FIELD timestamp ON TABLE covers TYPE datetime;",
    "DEFINE FIELD source ON TABLE passes_over TYPE string;",
    "DEFINE FIELD score ON TABLE passes_over TYPE number;",
    "DEFINE FIELD timestamp ON TABLE passes_over TYPE datetime;",
    "DEFINE FIELD source ON TABLE involves TYPE string;",
    "DEFINE FIELD score ON TABLE involves TYPE number;",
    "DEFINE FIELD timestamp ON TABLE involves TYPE datetime;",
    "DEFINE FIELD source ON TABLE connects_to TYPE string;",
    "DEFINE FIELD score ON TABLE connects_to TYPE number;",
    "DEFINE FIELD timestamp ON TABLE connects_to TYPE datetime;",
    "DEFINE FIELD source ON TABLE reports TYPE string;",
    "DEFINE FIELD score ON TABLE reports TYPE number;",
    "DEFINE FIELD timestamp ON TABLE reports TYPE datetime;",
    "DEFINE FIELD source ON TABLE near TYPE string;",
    "DEFINE FIELD score ON TABLE near TYPE number;",
    "DEFINE FIELD timestamp ON TABLE near TYPE datetime;",
    "DEFINE FIELD source ON TABLE targets TYPE string;",
    "DEFINE FIELD score ON TABLE targets TYPE number;",
    "DEFINE FIELD timestamp ON TABLE targets TYPE datetime;",
    "DEFINE FIELD source ON TABLE derived_from TYPE string;",
    "DEFINE FIELD score ON TABLE derived_from TYPE number;",
    "DEFINE FIELD timestamp ON TABLE derived_from TYPE datetime;",
];

pub async fn migrate(client: &GraphClient) -> anyhow::Result<()> {
    for table in ENTITY_TABLES {
        let statement = format!("DEFINE TABLE {table} SCHEMALESS;");
        client.db().query(statement).await?;
    }

    for table in RELATION_TABLES {
        let statement = format!("DEFINE TABLE {table} TYPE RELATION SCHEMALESS;");
        client.db().query(statement).await?;
    }

    for statement in FIELD_DEFINITIONS {
        client.db().query(*statement).await?;
    }

    client
        .db()
        .query("DEFINE INDEX zone_name_idx ON TABLE zone COLUMNS name;")
        .await?;

    Ok(())
}
