use axum::{http::StatusCode, Json};
use serde_json::Value;

/// Filtered from OurAirports' world-wide `airports.csv` (public domain —
/// "All data is released to the Public Domain", verified live 2026-08-13
/// against https://ourairports.com/data/, the primary source, not assumed
/// from the download mirror alone) to `large_airport`/`medium_airport` only:
/// the raw file is 85,892 rows, 80,620 of them helipads/small
/// airports/closed fields/seaplane bases/balloonports that this app has no
/// use for. The kept 5,272 rows are regenerated by re-running the same
/// filter against a fresh download — see `docs/plans/sources.md` for the
/// exact filter and field mapping.
const AIRPORTS_JSON: &str = include_str!("../../../data/airports/airports.json");

pub async fn get_airports() -> Result<Json<serde_json::Value>, StatusCode> {
    let mut payload: Value =
        serde_json::from_str(AIRPORTS_JSON).map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;

    if let Some(list) = payload.as_array_mut() {
        super::stable_ids::inject_stable_ids_in_array("airport", list);
    }

    Ok(Json(payload))
}
